# Generated by Django 5.2.14 on 2026-09-18 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ykphone", "0004_saveditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("paused_until", models.DateTimeField(null=True)),
                ("schedule", models.JSONField(default=dict)),
                ("announced_paused", models.BooleanField(default=False)),
                ("mobile_notifications", models.BooleanField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ykphone_notification_pause",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusExpiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("clear_at", models.DateTimeField(db_index=True)),
                ("status_text", models.TextField(default="")),
                ("emoji_name", models.TextField(default="")),
                ("emoji_code", models.TextField(default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ykphone_status_expiry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
